"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

def fib(n):
    memo = {0:1, 1:2}
    if not n in memo:
         memo[n] = fib(n-1) + fib(n-2)
    return memo[n]

if __name__ == '__main__':
    i = 0
    sum = 0
    while (fib(i) < 4 * 10**6):
        if fib(i) % 2 == 0:
            sum += fib(i)
        i += 1

    print(sum)
