# Henrik Grønbech

# https://projecteuler.net/problem=2

#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#


function sum_even_fibonacci_below_n(n)
    n1 = 1
    n2 = 2

    sum = 0
    while n1 <= n
        if n1 % 2 == 0
            sum += n1
            @info n1, sum
        end
        n1, n2 = n2, n1+n2
    end
    return sum
end


println(sum_even_fibonacci_below_n(4_000_000))
